package uk.ac.cam.bizrain.test.ui;

import java.awt.ComponentOrientation;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

import uk.ac.cam.bizrain.util.Pointer;

/**
 * 
 * Auto-Generated by WindowBuilder
 * 
 * PLS NO BRICK
 * 
 * @author btfs2
 *
 */
public class PanelNav extends JPanel {

	/**
	 * Used for stopping IDES complaining
	 * 
	 * And serialisation
	 */
	private static final long serialVersionUID = -4243122071569722634L;

	/**
	 * Create the panel.
	 */
	public PanelNav(Pointer<JPanel> pannelPointer, Pointer<Integer> idxPointer) {
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{0, 0, 0, 0, 0};
		gridBagLayout.rowHeights = new int[]{50, 0};
		gridBagLayout.columnWeights = new double[]{1.0, 1.0, 1.0, 1.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		setLayout(gridBagLayout);
		
		JButton buttonBack = new JButton("Back");
		buttonBack.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				idxPointer.set(idxPointer.get()-1);
			}
		});
		buttonBack.setIcon(new ImageIcon(PanelNav.class.getResource("/uk/ac/cam/bizrain/test/ui/fa-chevron-left-16.png")));
		GridBagConstraints gbc_buttonBack = new GridBagConstraints();
		gbc_buttonBack.fill = GridBagConstraints.BOTH;
		gbc_buttonBack.insets = new Insets(0, 0, 0, 5);
		gbc_buttonBack.gridx = 0;
		gbc_buttonBack.gridy = 0;
		add(buttonBack, gbc_buttonBack);
		
		JButton btnSettings = new JButton("Settings");
		btnSettings.setIcon(new ImageIcon(PanelNav.class.getResource("/uk/ac/cam/bizrain/test/ui/fa-cogs-16.png")));
		GridBagConstraints gbc_btnSettings = new GridBagConstraints();
		gbc_btnSettings.fill = GridBagConstraints.BOTH;
		gbc_btnSettings.insets = new Insets(0, 0, 0, 5);
		gbc_btnSettings.gridx = 1;
		gbc_btnSettings.gridy = 0;
		add(btnSettings, gbc_btnSettings);
		
		JButton btnDelete = new JButton("Delete");
		btnDelete.setIcon(new ImageIcon(PanelNav.class.getResource("/uk/ac/cam/bizrain/test/ui/fa-trash-16.png")));
		GridBagConstraints gbc_btnDelete = new GridBagConstraints();
		gbc_btnDelete.fill = GridBagConstraints.BOTH;
		gbc_btnDelete.insets = new Insets(0, 0, 0, 5);
		gbc_btnDelete.gridx = 2;
		gbc_btnDelete.gridy = 0;
		add(btnDelete, gbc_btnDelete);
		
		JButton btnForward = new JButton("Forward");
		btnForward.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
		btnForward.setIcon(new ImageIcon(PanelNav.class.getResource("/uk/ac/cam/bizrain/test/ui/fa-chevron-right-16.png")));
		GridBagConstraints gbc_btnForward = new GridBagConstraints();
		gbc_btnForward.fill = GridBagConstraints.BOTH;
		gbc_btnForward.gridx = 3;
		gbc_btnForward.gridy = 0;
		add(btnForward, gbc_btnForward);
		btnForward.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				idxPointer.set(idxPointer.get()+1);
			}
		});
	}

}
