package uk.ac.cam.bizrain.test.ui;

import java.awt.EventQueue;

import javax.swing.JFrame;
import java.awt.GridBagLayout;
import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import uk.ac.cam.bizrain.util.Pointer;

import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 * 
 * Auto-Generated by WindowBuilder
 * 
 * PLS NO BRICK
 * 
 * @author btfs2
 *
 */
public class TestWindow {

	private JFrame frame;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TestWindow window = new TestWindow();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public TestWindow() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		try {
			UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		
		frame = new JFrame();
		frame.setBounds(100, 100, 450, 600);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{434, 0};
		gridBagLayout.rowHeights = new int[]{80, 526, 0};
		gridBagLayout.columnWeights = new double[]{0.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{0.0, 0.0, Double.MIN_VALUE};
		frame.getContentPane().setLayout(gridBagLayout);
		
		JPanel panelNav = new PanelNav();
		GridBagConstraints gbc_panelNav = new GridBagConstraints();
		gbc_panelNav.fill = GridBagConstraints.BOTH;
		gbc_panelNav.insets = new Insets(0, 0, 5, 0);
		gbc_panelNav.gridx = 0;
		gbc_panelNav.gridy = 0;
		frame.getContentPane().add(panelNav, gbc_panelNav);
		
		JScrollPane scrollBody = new JScrollPane();
		scrollBody.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		scrollBody.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		GridBagConstraints gbc_scrollBody = new GridBagConstraints();
		gbc_scrollBody.fill = GridBagConstraints.BOTH;
		gbc_scrollBody.gridx = 0;
		gbc_scrollBody.gridy = 1;
		frame.getContentPane().add(scrollBody, gbc_scrollBody);
		
		Pointer<JPanel> bodyPointer = new Pointer<JPanel>(new PanelNewSchedule());
		scrollBody.setViewportView(bodyPointer.get());
	}

}
